import { SITE } from "@/lib/site";
import { SITEMAP_CACHE_SECONDS } from "@/lib/sitemap-xml";

/**
 * The stylesheet every sitemap references. Rank Math ships one XSL that
 * renders both the index and the individual URL sets as a readable table, so
 * opening a sitemap in a browser shows a page instead of raw XML. Same idea
 * here, styled to match the site.
 *
 * Note: browsers only apply an XSL stylesheet served from the same origin,
 * which is why this lives on the frontend rather than on a CDN host.
 */
export const dynamic = "force-static";

const STYLESHEET = `<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  exclude-result-prefixes="sitemap image">

  <xsl:output method="html" encoding="UTF-8" indent="yes"/>

  <xsl:template match="/">
    <html lang="th">
      <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <meta name="robots" content="noindex, follow"/>
        <title>XML Sitemap &#8212; ${SITE.name}</title>
        <style>
          :root { color-scheme: light; }
          * { box-sizing: border-box; }
          body {
            margin: 0;
            padding: 0 1rem 4rem;
            background: #faf8f5;
            color: #14110f;
            font: 15px/1.6 -apple-system, BlinkMacSystemFont, "Segoe UI",
                  "Noto Sans Thai", "Helvetica Neue", Arial, sans-serif;
          }
          .wrap { max-width: 1080px; margin: 0 auto; }
          header { padding: 2.5rem 0 1.5rem; border-bottom: 3px solid #14110f; }
          h1 {
            margin: 0;
            font-size: 1.9rem;
            font-weight: 800;
            letter-spacing: -0.02em;
          }
          h1 span { color: #ed2024; }
          .lede { margin: .75rem 0 0; max-width: 62ch; color: #55504b; }
          .lede a { color: #ed2024; }
          .meta {
            margin: 1.25rem 0 0;
            font-size: .8rem;
            text-transform: uppercase;
            letter-spacing: .08em;
            color: #86807a;
          }
          table {
            width: 100%;
            margin-top: 1.75rem;
            border-collapse: collapse;
            background: #fff;
            border: 1px solid #e7e2db;
          }
          th {
            text-align: left;
            font-size: .72rem;
            text-transform: uppercase;
            letter-spacing: .09em;
            color: #55504b;
            background: #f3efe9;
            padding: .7rem .9rem;
            border-bottom: 1px solid #e7e2db;
            white-space: nowrap;
          }
          td {
            padding: .65rem .9rem;
            border-bottom: 1px solid #f0ece6;
            vertical-align: top;
            word-break: break-word;
          }
          tr:last-child td { border-bottom: 0; }
          tr:hover td { background: #fdfbf8; }
          td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
          td.date, th.date { white-space: nowrap; color: #55504b; font-size: .85rem; }
          a { color: #14110f; text-decoration: none; }
          a:hover { color: #ed2024; text-decoration: underline; }
          footer {
            margin-top: 2rem;
            font-size: .8rem;
            color: #86807a;
          }
          @media (max-width: 640px) {
            th.date, td.date { display: none; }
          }
        </style>
      </head>
      <body>
        <div class="wrap">
          <header>
            <h1>XML Sitemap<span>.</span></h1>
            <p class="lede">
              รายการ URL สำหรับเครื่องมือค้นหา ไม่ได้มีไว้สำหรับผู้อ่านทั่วไป
              กลับไปที่ <a href="${SITE.url}">${SITE.name}</a>
            </p>
            <xsl:if test="sitemap:sitemapindex">
              <p class="meta">
                Sitemap index &#183;
                <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/>
                <xsl:text> sitemaps</xsl:text>
              </p>
            </xsl:if>
            <xsl:if test="sitemap:urlset">
              <p class="meta">
                <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/>
                <xsl:text> URLs &#183; </xsl:text>
                <xsl:value-of select="count(sitemap:urlset/sitemap:url/image:image)"/>
                <xsl:text> images</xsl:text>
              </p>
            </xsl:if>
          </header>

          <xsl:apply-templates select="sitemap:sitemapindex"/>
          <xsl:apply-templates select="sitemap:urlset"/>

          <footer>
            Generated by ${SITE.name}. Index:
            <a href="${SITE.url}/sitemap_index.xml">/sitemap_index.xml</a>
          </footer>
        </div>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="sitemap:sitemapindex">
    <table>
      <tr>
        <th class="num">#</th>
        <th>Sitemap</th>
        <th class="date">Last modified</th>
      </tr>
      <xsl:for-each select="sitemap:sitemap">
        <tr>
          <td class="num"><xsl:value-of select="position()"/></td>
          <td>
            <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
          </td>
          <td class="date"><xsl:value-of select="sitemap:lastmod"/></td>
        </tr>
      </xsl:for-each>
    </table>
  </xsl:template>

  <xsl:template match="sitemap:urlset">
    <table>
      <tr>
        <th class="num">#</th>
        <th>URL</th>
        <th class="num">Images</th>
        <th class="date">Last modified</th>
      </tr>
      <xsl:for-each select="sitemap:url">
        <tr>
          <td class="num"><xsl:value-of select="position()"/></td>
          <td>
            <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
          </td>
          <td class="num"><xsl:value-of select="count(image:image)"/></td>
          <td class="date"><xsl:value-of select="sitemap:lastmod"/></td>
        </tr>
      </xsl:for-each>
    </table>
  </xsl:template>
</xsl:stylesheet>
`;

export async function GET() {
  return new Response(STYLESHEET, {
    headers: {
      "Content-Type": "text/xsl; charset=utf-8",
      "X-Robots-Tag": "noindex, follow",
      "Cache-Control": `public, max-age=0, s-maxage=${SITEMAP_CACHE_SECONDS}, stale-while-revalidate=86400`,
    },
  });
}
